fbdevelopercircles/FbDevcCommunityContent

README.md
Tutorial series of famous book cracking the coding interview by Gayle Laakmann McDowell in collaboration with HackerRank added for FbDevC community. Enjoy 😉.
=> Cracking the Coding Interview tutorial series

DevCGlobalDirectory.md
Changes proposed in this pull request:
* Add DevC Bangkok to the list
=> Add DevC Bangkok to the list :bear:

README.md
Add handbook for front end developer
=> Add item in the article section

README.md
Added links to the Open Source learning path in the developercirclesresources.com
=> Re-arrange the main readme.md

DevCGlobalDirectory.md
This PR adds DevC Jakarta to the Developer Circles List.
Update the list only.
#<NUMBER>
Nothing
=> Add DevC Jakarta

README.md
Add a useful resource for learning basic front end knowledge.
N/A
I wrote the Tech Interview Handbook. Since it's here I think the Front End Interview Handbook would be useful too.
=> Add Front End Interview Handbook to Articles

README.md
This is one of my favorite resources.
Adds CS50 videos under Videos section
=> Added CS50 in Videos

DevCGlobalDirectory.md
=> Added DevC Uyo.

README.md
Adds a blogs section
discussion on #36
=> added blogs section

.github/PULL_REQUEST_TEMPLATE.md
updating PR template with friendlier questions
=> updated template

DevCGlobalDirectory.md
Cleaning up FB URL's in global directory
#63
=> removed facebook links

DevCGlobalDirectory.md
Updated DevCGlobalDirectory.md
#59
=> Updated DevCGlobalDirectory.md

DevCGlobalDirectory.md
=> Added DevC Buea

README.md
Add new podcasts to the list in README.md
- [Artificial Intelligence: AI Podcast](https://lexfridman.com/ai/) - A series of conversations about technology, science, and the human condition.
- [Software Engineering](https://www.se-radio.net/) - A podcast targeted at the professional software developer managed by the volunteers and staff of IEEE Software.
=> Add new podcasts to the list in README.md

DevCGlobalDirectory.md
I add DevC Taipei in the DevCGlobalDirectory.md
N/A
Facebook Developer Circle: Taipei's [Facebook group link](https://www.facebook.com/groups/DevCTaipei)
=> add DevC Taipei in DevCGlobalDirectory.md

DevCGlobalDirectory.md
Satya is a FB employee, not a lead. Also, Nelson took a break, so there is no Bangalore lead as of now.
N/A
=> updated global directory

DevCGlobalDirectory.md
Added Facebook DevC Santo Domingo informations
=> Added Facebook DevC Santo Domingo informations

README.md
Add interview preparation article link
#<NUMBER>
Link: https://github.com/Nabagata/interview-prep
=> Add interview article

DevCGlobalDirectory.md
fix #59
Adds DevC Owerri to Global directory
#59
=> Add Owerri to devc global directory

DevCGlobalDirectory.md
Added DevC Kingston Info in DevcGlobalDirectory.md
#59
=> Added DevC Kingston - GlobalDirectory

DevCGlobalDirectory.md
What does this PR do?
I add DevC Algiers in the DevCGlobalDirectory.md
Any relevant issues this PR addresses? (optional)
N/A
Any background context you want to add?
Facebook Developer Circle: Algiers [Facebook group link](https://web.facebook.com/groups/DevCAlgiers)
=> adding devc algiers

README.md
- Added link to a Spanish community tech talks youtube channel to the video section
=> Added link to Streamelopers youtube channel

README.md
=> Added Heroku tool and DEV.to blogs.

README.md
Deno has arrived recently and it's getting fame. I added Deno's concise introduction article in **README**
None
No
=> Add Deno Article

README.md
Added an amazing React JS course
- Added an amazing React JS course for beginners in the videos section
#<NUMBER>
=> Update README.md in the Videos Section

README.md
Contributed to README podcasts lists, added "the stack overflow podcast" and "google cloud platform podcast"
#1
=> added podcast-list

README.md
- Added Eloquent Modern JavaScript in Book Section.
None
I am making this PR in context of Facebook Open Source Immersion.
=> Added modern Javascript Programming book

README.md
Will add the babel to the tools list
#<NUMBER>
=> Added Babel to tools list

DevCGlobalDirectory.md
DevC Kolkata is added in DevC Global Directory .
#<NUMBER>
=> Update DevCGlobalDirectory.md - added DevC Kolkata 

README.md
Adds a  podcast link in the  Contents-podcast section 
Adds an article link to the Contents-Articles section
#<NUMBER>
=> Added a podcast in the Contents section

DevCGlobalDirectory.md
Adds Raipur DevC in the list of Developer Circles.
#<NUMBER>
=> Added DevC Raipur section.

DevCGlobalDirectory.md
Hi, I have completed the profile description of Lead Devc of douala by adding the link to the organization that we have created on github for our community
Hi, This PR add the link the link to the organization that was created for our communty Devc Douala, to the profile of your Lead Herve Dzeudjouo.
#<NUMBER>
=> Completed the profile description of your Lead Devc of douala

DevCGlobalDirectory.md
What does this PR do?
I add DevC Tunis in the DevCGlobalDirectory.md
Any relevant issues this PR addresses? (optional)
N/A
Any background context you want to add?
Facebook Developer Circle: Tunis [Facebook group link](https://www.facebook.com/groups/DevCTunis)
=>  adding devc tunis

README.md
-Added Swagger under Tools section
#<NUMBER>
=> Added Swagger under Tools section in README.md

DevCGlobalDirectory.md
Add Devc Eldoret to the DevCGlobalDirectory
N/A
=> Added Devc Eldoret

DevCGlobalDirectory.md
I add DevC Trivandrumin the DevCGlobalDirectory.md including the facebook group
- added DevC Trivandrum to the directory
N/A
#<NUMBER>
DevC Trivandrum Facebook Group : https://www.facebook.com/groups/DevCTRV/
=> adding DevC Trivandrum

README.md
Added TypeRacer to list of fun activities in README
also corrected 2 typos in the README
#<NUMBER>
=> Added TypeRacer to list of fun activities in README

README.md
- Added Hashnode a blogging platform for developers in blog section
- No
- I am making this PR in context of Facebook Open Source Immersion.
=> Added blogging platform in blog section

README.md
update link of ebook "You Don't Know JS Yet" in readme
=> update url of ebook in readme

DevCGlobalDirectory.md
Adds DevC Nairobi community information to DevCGlobalDirectory.md
#<NUMBER>
=> Tabitha kavyu patch 1

README.md
What does this PR do?
Adding one more tool to the list
Any background context you want to add?
It is a tool for editing markdown texts
=> new Tool to README

README.md
=> Added `Pure React` to list of Books.

DevCGlobalDirectory.md, README.md
Earlier I was not sure about the lead of DevC Raipur, now it's corrected to the original one.
#<NUMBER>
=> fix: Corrected DevC Raipur lead name.

README.md
=> Add thisdev podcast

README.md
add reference book "The Clean Coder: A Code of Conduct for Professional Programmers" in readme. It is a great book!
=> add reference book in readme

README.md
Adds Codepen blog to blog section in README
=> added Codepen blog to blog section

README.md
I have added two new books in book-section in Readme.md file, which can be used in preparing for technical interviews and competitive programming.
#<NUMBER>
None
=> added new books in book-section

README.md
=> Added devswag site in fun section

DevCGlobalDirectory.md
Adds DevC Kathmandu Details
#<NUMBER>
=> Add DevC Kathmandu details

README.md
Adds LogRocket Blog to the Blogs section
#<NUMBER>
=> Added a blog in the Blog section

DevCGlobalDirectory.md
Hi, This PR adds DevC Yaounde Leads in the file DevCGlobalDirectory.md
Hi, This PR adds DevC Yaounde Leads in the file DevCGlobalDirectory.md
#<NUMBER>
This is a PR for the Open Source Immersion program
=> Added DevC Yaounde Leads

README.md
Points the user to a book they can read to learn python
=> add a book on python

README.md
Shows the link to Airbnb's Engineering blog
=> add a link to airbnb's engineering blog

README.md
Add GitHub Guides and Correct typo mistake
=> Add GitHub Guides and Correct typo mistake

README.md
Added a hackathons section.
I have added a hackathons section where all the coding contests and competition sites will be displayed.
=> Added hackathons section

README.md
=> Added CodeSandBox.io into the tools section of the readme.md file

README.md
=> added facebook ai blog

README.md
This PR adds 2 really nice resources to the README.md file to be accessed
- A TED TALK on grit
- A sketch showing growth vs fixed mindset
These are valuable resources to help learners overcome adversity
#<NUMBER>
- Growth mindset is the idea that the brain's capacity isn't fixed and that all skills are learnable if you work hard enough failing your way to success
=> adds resources on grit and growth mindset

DevCGlobalDirectory.md
Hi, Updated DevC Yaounde's info with github profile link in DevCGlobalDirectory.md
#<NUMBER>
=> Added DevC Yaounde's github profile link to the DevCGlobalDirectory.md

README.md
=> Web Development Technologies

README.md
Addded `Road To Redux by Robin Wieruch to list of Books`
#<NUMBER>
=> Addded `Road To Redux by Robin Wieruch to list of Books`

README.md
Add a new tool to the README
N/A
An alternative tool for Postman and Swagger
=> Insomnia in Tools

README.md
Hi, Add a new tool to the README. An alternative tool for Postman and Swagger
#
=> Add Insomnia to Tools list

README.md
=> Add Stephen Judes blog

README.md
Hi this pr add Spark tutorials to the readme.md file
#<NUMBER>
=> Add Spark AR tutorials

README.md
I have added a unique site for understanding machine learning in a beautiful way.
=> Added a machine learning website to Blogs section

README.md
Added new video about Spark AR
=> Updated the videos section

README.md
An updated list of blogs/ blog sites and their descriptions, and a fix on a broken link
#169 
A fix to issue #168 
Curated list from the most common tools and frameworks' blogs (official blogging sites) describing new technologies or how to use newly updated versions
=> Add blogs to README

README.md
Includes these blog resources:
- Chrome Developers Blog 
- IBM's Data and AI Blogs
- Wesbos's Blog 
- Wake Up And Code
=> added four blog resources

DevCGlobalDirectory.md
This PR adds information about Facebook Developer Circle: Dhaka 
#<NUMBER>
=> Add DevC Dhaka info

README.md
This PR adds 2 articles about React. 
No. It doesn't address any issue.
#<NUMBER>
=> Added two articles on React

DevCGlobalDirectory.md, README.md
=> modify readme.md and devcGlobaldirectory

README.md
Added a link to web dev site so users can  Explore structured learning paths to discover everything you need to know about building for the modern web.
#<NUMBER>
https://github.com/devcuyo
https://github.com/didicodese
=> Added a link to web dev blog 

README.md
adds an awesome challenge tool for frontend developers
#<NUMBER>
=> Franklin contribute

README.md
- Added Code battle section which will help people to participate in the code battle conducted in the given site links.
=> Added Code Battle Section

README.md
***Added resources/links under the following section:***
- Blogs: 
- @praveenscience - Tech blog including Git shortcuts and many more.
- Tools: 
- Repl.it - Code and collaborate, without friction.
- Emmet - Emmet — the essential toolkit for web-developers
- Videos : YouTube Channel Link
- Open Source Developer Advocate, BELIEVES OPEN SOURCE IS FOR EVERYONE! YES YOU!
- Techie-Workshops, Techie-Workshops by Praveen Kumar
- LetsUpgrade, A Technology Community for Career Acceleration
- Hackathons:
- MLH - Amazing platform for various workshops and hackathons
- HackerEarth - Hackathons which help you put your coding skills to work. Solve interesting business problems and real-world challenges.
- spotle.ai - Recognizing the best talents in Artificial Intelligence and Technology.
- **Added a …
=> feat(links): Added OpenSource Section + Amazing Resources

README.md
Added Clash of Code in Code Battle section.
=> Added Clash of Code in Code battle section
